version: '3.8'

services:
  db:
    image: postgres:17
    container_name: music_db
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
      POSTGRES_DB: music_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U music_user -d music_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: